# Generated by Django 4.1.2 on 2023-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("catid", models.AutoField(primary_key=True, serialize=False)),
                ("catname", models.CharField(max_length=50, unique=True)),
                ("caticonname", models.CharField(max_length=100)),
            ],
        ),
    ]
